### PR TITLE
Fix the misuse of Rf_mkCharLenCE()

### PR DESCRIPTION
**Pull request by yutannihilation**

### CODE REVIEW

**Comment by tom91136** [comment]
Hi, I'm trying to use this package on a AArch64 Linux machine and I can see the compilation is resolved by this PR, thanks.
Currently the CRAN release is 0.1.6 which doesn't include this commit, are there any plans for 0.1.7 at some point?

**Comment by yutannihilation** [comment]
Maybe you are talking about string2path?

**Comment by tom91136** [comment]
Ah sorry, I had two tabs open investigating this and commented on the wrong package. Yes I'm referring to string2path.

**Comment by yutannihilation** [comment]
I see. I'll consider releasing the new version on CRAN. Thanks for the notice.

**Comment by tom91136** [comment]
Thank you!

**Pull request merged**
