### PR TITLE
Improve configure

### PR DESCRIPTION
**Pull request by yutannihilation**
* Check cargo command
* Print the version of `cargo` and `rustc`

### CODE REVIEW

**Comment by eitsupi** [comment]
Some thoughts from <https://github.com/PRQL/prqlc-r>:

- `$HOME/.cargo/bin` should be added to `PATH` as like https://github.com/yutannihilation/savvy/blob/a357d4f80a15b514699411f0e6dfd0ac528b7099/savvy-bindgen/src/gen/templates/Makevars.in#L21
- `configure.win` (show info for windows), `cleanup` (R CMD check may complain if `Makevars` is generated but not removed) are not needed?

**Comment by yutannihilation** [comment]
Oh, thanks. `$HOME/.cargo/bin` is probably better and consistent.

> * `configure.win`

I think this doesn't contain settings specific to Windows.

> * `cleanup`

I forgot this, thanks for catching.

**Comment by yutannihilation** [comment]
Ah, you are right... I think I don't want to create `src/Makevars` on Windows, so I'll keep as it is for now.

**Comment by eitsupi** [comment]
> Ah, you are right... I think I don't want to create `src/Makevars` on Windows, so I'll keep as it is for now.

I don't think users will see this, because `Makevars` will be removed by calling `cleanup` in `cleanup.win` (by the way, prqlr's `cleanup.win` doesn't seem to remove `Makevars` due to my copy error, but there doesn't seem to be a warning).

Well, in any case, it is no big deal.

**Comment by yutannihilation** [comment]
Added some words here.

https://github.com/yutannihilation/savvy/blob/dea29d3426c8208d3dbfc06d3df3a95c98dae5a8/savvy-bindgen/src/gen/templates/configure#L1-L4

https://github.com/r-rust/hellorust also doesn't have `configure.win` or `cleanup.win`. So, as long as this package is on CRAN, we can consider this is fine in terms of the CRAN policy.

**Comment by eitsupi** [comment]
I see, that makes sense.

**Comment by eitsupi** [comment]
It seems that `hellorust` has been removed from CRAN, and since it seems that the rustc version check has been started in R CMD check, I think we need to display the version in Windows (`prqlr` does not seem to have a warning on CRAN).
https://github.com/r-devel/r-svn/commit/6114d4126434c056b476cbc5db2657536c153d9a

**Comment by yutannihilation** [comment]
Oh, RIP hellorust... Okay, I will implement the .win files.

**Pull request merged**
